# Generated by Django 3.0.14 on 2023-06-19 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=64, verbose_name='问题名称')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children',
                                             to='account.Classify')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('content', models.TextField(verbose_name='答案内容')),
                ('qustion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer',
                                              to='account.Question', verbose_name='关联的问题')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
