# Generated by Django 3.0.14 on 2023-06-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0004_answer_classify_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collect_ques',
            field=models.ManyToManyField(to='account.Question'),
        ),
    ]
